# Generated by Django 4.2.16 on 2024-11-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('etc_note', models.TextField()),
                ('join_deny', models.CharField(max_length=10)),
                ('join_member', models.CharField(max_length=100)),
                ('join_way', models.CharField(max_length=100)),
                ('spcl_cnd', models.TextField()),
                ('dcls_strt_day', models.DateField()),
            ],
        ),
    ]
