# Generated by Django 4.2.16 on 2024-11-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StandardizedTermDeposit',
            fields=[
                ('fin_prdt_cd', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('min_join_amount', models.FloatField(null=True)),
                ('max_join_amount', models.FloatField(null=True)),
                ('join_period', models.CharField(max_length=100)),
                ('interest_rate', models.FloatField(null=True)),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
            ],
        ),
    ]
