# Generated by Django 4.2.16 on 2024-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedTermDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('min_join_amount', models.FloatField(null=True)),
                ('max_join_amount', models.FloatField(null=True)),
                ('join_period', models.TextField()),
                ('interest_rate', models.FloatField(null=True)),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FinanceProduct',
        ),
    ]
