# Generated by Django 4.2.16 on 2024-11-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_standardizedtermdeposit_delete_financeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtermdeposit',
            name='join_period',
            field=models.TextField(default='정보없음'),
        ),
    ]
