# Generated by Django 4.2.16 on 2024-11-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_standardizedtermdeposit_join_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardizedtermdeposit',
            name='join_member',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='standardizedtermdeposit',
            name='join_way',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='standardizedtermdeposit',
            name='spcl_cnd',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
