# Generated by Django 4.2.16 on 2024-11-20 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField(null=True)),
                ('crdt_prdt_type_nm', models.TextField()),
                ('dcls_strt_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('loan_inci_expn', models.TextField()),
                ('erly_rpay_fee', models.TextField()),
                ('dly_rate', models.TextField()),
                ('loan_lmt', models.TextField(null=True)),
                ('dcls_strt_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('etc_note', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('dcls_strt_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.TextField()),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('etc_note', models.TextField()),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField()),
                ('join_way', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('dcls_strt_day', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermDepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.termdeposit')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.savings')),
            ],
        ),
        migrations.CreateModel(
            name='LoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('mrtg_type_nm', models.TextField(blank=True, default='전세자금대출', null=True)),
                ('rpay_type_nm', models.TextField()),
                ('lend_rate_type_nm', models.TextField()),
                ('lend_rate_min', models.FloatField(null=True)),
                ('lend_rate_max', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.loanproducts')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLoanOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('crdt_lend_rate_type_nm', models.TextField()),
                ('crdt_grad_1', models.FloatField(null=True)),
                ('crdt_grad_4', models.FloatField(null=True)),
                ('crdt_grad_5', models.FloatField(null=True)),
                ('crdt_grad_6', models.FloatField(null=True)),
                ('crdt_grad_10', models.FloatField(null=True)),
                ('crdt_grad_11', models.FloatField(null=True)),
                ('crdt_grad_12', models.FloatField(null=True)),
                ('crdt_grad_13', models.FloatField(null=True)),
                ('crdt_grad_avg', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.creditloanproducts')),
            ],
        ),
    ]
